### ISSUE TITLE
Skate Possible miss location?  

### ISSUE THREAD

**Issue by TooFast4ya** [BigApex/rse-ooa-decrypt#1]
Are you sure they store license there?
I've got 2 pc and the 2 don't have anything in C:\ProgramData\Electronic Arts

Skate 7/5

**Comment by mrsteyk** [comment]
You never launched it I guess. If you launch the game (and you own it) DLF must be in programdata under EA's folder, that's how OOA works.

**Comment by TooFast4ya** [comment]
I lunched the game multiple times to try to get it spit out a .DLF,
Still nothing, 

Also I don't own it cause it's not out,
Is it still suppose to spit out a DLF?

Here's my discord : Cid#7584 
Let's talk on there

Sorry to bother you.

**Comment by mrsteyk** [comment]
You don't own it. You can't own that game nowadays, so all your attempts will be futile.
Case closed.
/thread
